# Generated by Django 3.1.2 on 2020-10-31 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import qualification.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=25, verbose_name='Фамилия')),
                ('middle_name', models.CharField(max_length=25, verbose_name='Отчество')),
                ('serial_number', models.IntegerField(unique=True, verbose_name='Серийный номер')),
                ('date_birth', models.DateField(verbose_name='Дата рождения')),
                ('place_birth', models.CharField(max_length=125, verbose_name='Место рождения')),
                ('date_issue', models.DateField(verbose_name='Дата выдачи')),
                ('issued_by', models.CharField(max_length=75, verbose_name='Кем выдан')),
                ('registration_address', models.CharField(max_length=75, verbose_name='Адрес регистрации')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passport', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Паспорт',
                'verbose_name_plural': 'Паспорта',
                'ordering': ['first_name'],
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, verbose_name='Статус подтверждения квалификации')),
                ('confirm_rules', models.BooleanField(default=False, verbose_name='Подтверждение присоединения к правилам')),
                ('document', models.FileField(null=True, upload_to=qualification.models.qualification_directory_path, verbose_name='Документ о квалификации')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qualification', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Квалификация',
                'verbose_name_plural': 'Квалификации',
            },
        ),
        migrations.CreateModel(
            name='PassportImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to=qualification.models.passport_directory_path, verbose_name='Фотография')),
                ('passport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passport_image', to='qualification.passport')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
            },
        ),
    ]
